# Generated by Django 3.0.4 on 2020-04-02 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20200402_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264, unique=True)),
                ('userpassword', models.CharField(max_length=32)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Webpage')),
            ],
        ),
    ]
